name: blockbyte
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  aspen_assets: any
  html_unescape: any
  js: any
  # vdmc: any
  # vue: any
  vue: ^0.4.0
dependency_overrides:
  # vue:
    # path: /code/vuedart/vue
    # git: "https://github.com/kirbyfan64/vuedart.git"
  vdmc:
    path: /code/vdmc/vdmc
  # scopify:
    # path: /code/scopify
  # scopify:
    # path: /home/ryan/scopify
  # pygments:
    # path: /home/ryan/pygments-dart
  aspen_assets:
    path: /code/aspen/assets
  protic:
    path: /code/protic/protic
dev_dependencies:
  build_runner: any
  build_web_compilers: any
