name: blockbyte
dependencies:
  aspen_assets: any
  browser: any
  dart_to_js_script_rewriter: any
  js: any
  protic_transformer: any
  pygments: ^0.1.3
  vue2: any
dependency_overrides:
  vue2:
    # path: /home/ryan/vuedart
    git: "https://github.com/kirbyfan64/vuedart.git"
  # scopify:
    # path: /home/ryan/scopify
  # pygments:
    # path: /home/ryan/pygments-dart
  # protic:
  #   path: /home/ryan/protic/protic
  # protic_transformer:
  #   path: /home/ryan/protic/protic_transformer
transformers:
  - protic_transformer
  - pygments:
      classes:
        - "pygments":
            re: "(.*)"
  - vue2:
      entry_points:
        - web/index.dart
        - web/tags.dart
        - web/page.dart
        - web/pages/katex.dart
  - dart_to_js_script_rewriter
